name: SSH Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      # Step 2: Set up SSH key for the deployment
      - name: Set up SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}  # The server's IP or domain (set in GitHub secrets)
          username: ${{ secrets.SSH_USERNAME }}  # SSH username for the server (set in GitHub secrets)
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key (set in GitHub secrets)
          port: 22  # Default SSH port, change if using a different port
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Optional: Passphrase for the private key (if it's encrypted)

      # Step 3: Deploy the code or run any necessary commands on the remote server
      # Example of running a command after successful SSH connection
      - name: Run deployment commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /path/to/your/project  # Change this to your project path on the server
            git pull origin main      # Example command to pull the latest changes
            docker-compose up -d     # Example command to restart a service (if using Docker Compose)
            # Add other commands as needed


