name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u smusthaf20 --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t smusthaf20/wisecow .
        docker push smusthaf20/wisecow

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/wisecow-app
          git pull
          kubectl apply -f k8s/
          kubectl apply -f k8s/ingress.yaml

