name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from your repo

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform support

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u smusthaf20 --password-stdin

    - name: Build and Push Docker image to DockerHub
      run: |
        docker build -t smusthaf20/wisecow .
        docker push smusthaf20/wisecow

    - name: Set up SSH connection and deploy to Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}  # Set the SSH host (e.g., 10.10.110.19)
        username: ${{ secrets.USERNAME }}  # Set the SSH username
        key: ${{ secrets.PRIVATE_KEY }}  # SSH private key to authenticate
        port: 22  # Default SSH port (you can change if needed)
        script: |
          # Navigate to your app directory on the Kubernetes server
          cd ~/wisecow
          
          # Pull the latest code from your GitHub repository
          git pull origin main
          
          # Rebuild and restart the Docker containers (e.g., using Docker Compose or directly with Docker)
          docker compose down  # Stop containers
          docker compose up -d --build  # Rebuild and start containers in detached mode

    - name: Clean up
      run: docker system prune -f  # Optional: Clean up unused Docker images, containers, etc.

